### ISSUE TITLE
Escaped quotes in text are not handled properly

### ISSUE THREAD

**Issue by aienabled** [GerhardvanZyl/Steam-VDF-Parser#1]
Hello!

I've noticed that if there is `\"` char in the text entry it's handled as regular `\` and `"` which results in incorrect VDF parsing.
For example try parsing this text:
```
"desc"
{
	"english"	"Richard wrote an article that pleased the Breakpoint fraction."
	"russian"	"Ричард написал статью, которую одобрили сторонники \"«Переломного момента»\"."
	"german"	"Richard hat einen Artikel geschrieben, der Breakpoint gefällt."
}
```

Regards!

**Comment by GerhardvanZyl** [comment]
Thanks for bringing it to my attention. 
Fixed and released as version 1.0.2.
